version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Retirer les volumes qui écrasent l'exécutable
    environment:
      - LANG=fr
